<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="MasLazu.AspNet.Framework.EfCore" Version="1.0.0-preview.9" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\MasLazu.AspNet.Authorization.Page.Domain\MasLazu.AspNet.Authorization.Page.Domain.csproj" />
  </ItemGroup>

</Project>
